### ISSUE TITLE
fungsi point in polygon

### ISSUE THREAD

**Issue by iingLK** [fiakoenjiniring/feidlambda#29]
Bisa juga ditambahkan, metode Ray-casting untuk ngecek point masuk dalam sebuah polygon tertutup. Ini dalam long-run, bisa dipakai untuk analisa grafik yang membutuhkan human visual. i.e. kolom diagram interaksi 2D, windrose, responspektra. Untuk yang responspektra kayaknya susah kalau xl based, kecuali kalau sudah bisa kayak GIS ngerubah longlat ke cartesian coord

Untuk saat ini, yang sudah dicoba seperti ini,
```
=LET(
    xp, E5,
    yp, F5,
    data, $B$5:$C$24,
    data1, DROP(data, -1),
    data2, DROP(data, 1),
    data3, HSTACK(data1, data2),
    _x1, CHOOSECOLS(data3, 1),
    _y1, CHOOSECOLS(data3, 2),
    _x2, CHOOSECOLS(data3, 3),
    _y2, CHOOSECOLS(data3, 4),
    container1, (yp < _y1) <> (yp < _y2),
    container2, _x1 + (yp - _y1) / (_y2 - _y1) * (_x2 - _x1) > xp,
    container3, IFERROR(container1 * container2 = 1, FALSE),
    MOD(SUM(IF(container3, 1, 0)), 2) = 1
) * 1
```
inside jika 1, outside jika 0

implementasi ke dalam lambda bisa dalam bentuk
`=lambda(xp,yp,data)`
xp,yp adalah point koordinat yang akan di cek,
data adalah polygon tertutupnya

**Comment by taruma** [comment]
ini juga akan dibuat versi untuk contribnya juga. dirilis berbarengan dengan v0.4.0
